In [1]:
import pandas as pd

In [2]:
path = r'../C3-ai-Location-IDs.xlsx'

In [3]:
xl = pd.ExcelFile(path)

In [4]:
#Documentation
xl.sheet_names

['PPMS Updates',
 'OutbreakLocations - all',
 'New City Mapping',
 'Metrics',
 'International Census',
 'IBM Weather',
 'WB Finance',
 'India',
 'PlaceIQ',
 'Country IDs',
 'Province & State IDs',
 'County IDs',
 'County Lat-Long',
 'NYT All-Cause',
 'Oxford',
 'City IDs',
 'Swayable',
 'BLS',
 'CTP',
 'US Census County Demographics',
 'CDC Demographics',
 'OppInsights',
 'BEA',
 'Realtor.com']

In [5]:
#using countries:
countries = xl.parse('Country IDs', header=2)

In [6]:
# countries in data
countries.shape

(190, 23)

In [7]:
countries.head()

,Country id,JHU,COVID Tracking Project,NYT: Case Counts,ECDC,WHO,Apple,University of Washington,COVID19 India,Dipartimento della Protezione Civile,...,Google,Corona Data Scraper,NYT: All Cause Mortality,University of Oxford OxCGRT,US Census Bureau: International Census,Swayable,US Bureau of Labor Statistics,Bureau of Economic Analysis,Opportunity Insights,US CDC: Select Demographic Characteristics
0,UnitedStates,X,NaN,X,X,X,X,X,NaN,NaN,...,X,X,X,X,X,X,NaN,X,X,X
1,China,X,NaN,X,X,X,NaN,NaN,NaN,NaN,...,NaN,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,X,NaN,X,X,X,NaN,NaN,NaN,NaN,...,X,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN
3,Albania,X,NaN,X,X,X,X,NaN,NaN,NaN,...,NaN,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN
4,Algeria,X,NaN,X,X,X,NaN,NaN,NaN,NaN,...,NaN,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN

In [8]:
#countries without JHU
countries.JHU.isnull().sum()

6

In [9]:
#List: countrie without JHU
countries[countries['JHU'].isnull()]

,Country id,JHU,COVID Tracking Project,NYT: Case Counts,ECDC,WHO,Apple,University of Washington,COVID19 India,Dipartimento della Protezione Civile,...,Google,Corona Data Scraper,NYT: All Cause Mortality,University of Oxford OxCGRT,US Census Bureau: International Census,Swayable,US Bureau of Labor Statistics,Bureau of Economic Analysis,Opportunity Insights,US CDC: Select Demographic Characteristics
72,Guernsey,NaN,NaN,X,X,X,X,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
87,Jersey,NaN,NaN,X,X,X,X,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
186,Comoros,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,X,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN
187,Lesotho,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN
188,NorthernMarianaIslands,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,Tajikistan,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,...,X,X,NaN,X,X,NaN,NaN,NaN,NaN,NaN

In [10]:
countries.isnull().sum()

Country id                                      0
JHU                                             6
COVID Tracking Project                        190
NYT: Case Counts                                0
ECDC                                            6
WHO                                            41
Apple                                         128
University of Washington                      145
COVID19 India                                 189
Dipartimento della Protezione Civile          189
South Korea Dataset                           189
The World Bank: Global Health Statistics       11
US Census Bureau: Demographic Estimates       189
Google                                         62
Corona Data Scraper                             3
NYT: All Cause Mortality                      169
University of Oxford OxCGRT                    23
US Census Bureau: International Census          4
Swayable                                      189
US Bureau of Labor Statistics                 190
Bureau of Economic Analysis                   189
Opportunity Insights                          189
US CDC: Select Demographic Characteristics    189
dtype: int64

In [11]:
#NYT...

### PL

In [12]:
xl.sheet_names

['PPMS Updates',
 'OutbreakLocations - all',
 'New City Mapping',
 'Metrics',
 'International Census',
 'IBM Weather',
 'WB Finance',
 'India',
 'PlaceIQ',
 'Country IDs',
 'Province & State IDs',
 'County IDs',
 'County Lat-Long',
 'NYT All-Cause',
 'Oxford',
 'City IDs',
 'Swayable',
 'BLS',
 'CTP',
 'US Census County Demographics',
 'CDC Demographics',
 'OppInsights',
 'BEA',
 'Realtor.com']

In [13]:
#Get province & state
var = 'Province & State IDs'
df = xl.parse(var, header=2)

In [14]:
df.shape

(1603, 26)

In [15]:
df.head()

,Province or State id,Province or State,Country,JHU,COVID Tracking Project,NYT: Case Counts,ECDC,WHO,Apple,University of Washington,...,Corona Data Scraper,University of Oxford CGRT,PlaceIQ,US Census Bureau: International Census,Realtor.com,Bureau of Economic Analysis,Swayable,Opportunity Insights,US CDC: Select Demographic Characteristics,COVID Racial Data Tracker
0,AustralianCapitalTerritory_Australia,AustralianCapitalTerritory,Australia,X,NaN,NaN,NaN,NaN,X,NaN,...,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Auckland_Australia,Auckland,Australia,NaN,NaN,NaN,NaN,NaN,X,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Externalterritories_Australia,Externalterritories,Australia,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,JervisBayTerritory_Australia,JervisBayTerritory,Australia,X,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NewSouthWales_Australia,NewSouthWales,Australia,X,NaN,NaN,NaN,NaN,X,NaN,...,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.columns

Index(['Province or State id', 'Province or State', 'Country ', 'JHU',
       'COVID Tracking Project', 'NYT: Case Counts', 'ECDC', 'WHO', 'Apple',
       'University of Washington', 'COVID19 India',
       'Dipartimento della Protezione Civile', 'South Korea Dataset',
       'The World Bank: Global Health Statistics',
       'US Census Bureau: Demographic Estimates', 'Google',
       'Corona Data Scraper', 'University of Oxford CGRT', 'PlaceIQ',
       'US Census Bureau: International Census', 'Realtor.com',
       'Bureau of Economic Analysis', 'Swayable', 'Opportunity Insights',
       'US CDC: Select Demographic Characteristics',
       'COVID Racial Data Tracker'],
      dtype='object')

In [17]:
col = 'Country '
df[col].isnull().sum()

0

In [18]:
df[df[col].isnull()]

Empty DataFrame
Columns: [Province or State id, Province or State, Country , JHU, COVID Tracking Project, NYT: Case Counts, ECDC, WHO, Apple, University of Washington, COVID19 India, Dipartimento della Protezione Civile, South Korea Dataset, The World Bank: Global Health Statistics, US Census Bureau: Demographic Estimates, Google, Corona Data Scraper, University of Oxford CGRT, PlaceIQ, US Census Bureau: International Census, Realtor.com, Bureau of Economic Analysis, Swayable, Opportunity Insights, US CDC: Select Demographic Characteristics, COVID Racial Data Tracker]
Index: []

[0 rows x 26 columns]

In [19]:
list(df[col].unique())

['Australia',
 'Canada',
 'China',
 'United States',
 'United Kingdom',
 'France',
 'Denmark',
 'Netherlands',
 'Italy',
 'India',
 'KoreaSouth',
 'Germany',
 'Spain',
 'Austria',
 'Belgium',
 'Brazil',
 'Czechia',
 'Estonia',
 'Japan',
 'Latvia',
 'Lithuania',
 'Panama',
 'Poland',
 'Russia',
 'Slovenia',
 'SouthAfrica',
 'Sweden',
 'Switzerland',
 'Ukraine',
 'Argentina',
 'Bahrain',
 'BosniaandHerzegovina',
 'Colombia',
 'Cuba',
 'Greece',
 'Honduras',
 'Hungary',
 'Iceland',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Jordan',
 'Kenya',
 'Lebanon',
 'Luxembourg',
 'Mexico',
 'Monaco',
 'New Zealand',
 'Nigeria',
 'NorthMacedonia',
 'Pakistan',
 'Peru',
 'Philippines',
 'Qatar',
 'Singapore',
 'Thailand',
 'Tunisia',
 'Turkey',
 'UnitedKingdom',
 'Vietnam',
 'Zambia',
 'Barbados',
 'Bulgaria',
 'Chile',
 'Croatia',
 'Egypt',
 'Finland',
 'Indonesia',
 'Kuwait',
 'Mauritius',
 'Norway',
 'Portugal',
 'Romania',
 'SaudiArabia',
 'Slovakia',
 'UnitedArabEmirates',
 'Uruguay',
 'Taiwan*']

In [20]:
#Location id
df[df[col]=='Nigeria']

,Province or State id,Province or State,Country,JHU,COVID Tracking Project,NYT: Case Counts,ECDC,WHO,Apple,University of Washington,...,Corona Data Scraper,University of Oxford CGRT,PlaceIQ,US Census Bureau: International Census,Realtor.com,Bureau of Economic Analysis,Swayable,Opportunity Insights,US CDC: Select Demographic Characteristics,COVID Racial Data Tracker
884,Niger_Nigeria,Niger,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293,Zamfara_Nigeria,Zamfara,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1294,Yobe_Nigeria,Yobe,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1295,Taraba_Nigeria,Taraba,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1296,Rivers_Nigeria,Rivers,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,Sokoto_Nigeria,Sokoto,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1298,Oyo_Nigeria,Oyo,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1299,Enugu_Nigeria,Enugu,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1300,Ekiti_Nigeria,Ekiti,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1301,Edo_Nigeria,Edo,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1302,Ebonyi_Nigeria,Ebonyi,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1303,Delta_Nigeria,Delta,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1304,CrossRiver_Nigeria,CrossRiver,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1305,FederalCapitalTerritory_Nigeria,FederalCapitalTerritory,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1306,Borno_Nigeria,Borno,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1307,Bayelsa_Nigeria,Bayelsa,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1308,Bauchi_Nigeria,Bauchi,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1309,Anambra_Nigeria,Anambra,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1310,AkwaIbom_Nigeria,AkwaIbom,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1311,Adamawa_Nigeria,Adamawa,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1312,Abia_Nigeria,Abia,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1313,Benue_Nigeria,Benue,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1314,Plateau_Nigeria,Plateau,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1315,Kaduna_Nigeria,Kaduna,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1316,Kogi_Nigeria,Kogi,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1317,Osun_Nigeria,Osun,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1318,Ondo_Nigeria,Ondo,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1319,OgunState_Nigeria,OgunState,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1320,Nasarawa_Nigeria,Nasarawa,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1321,Lagos_Nigeria,Lagos,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1322,Kwara_Nigeria,Kwara,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1323,Gombe_Nigeria,Gombe,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1324,Imo_Nigeria,Imo,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1325,Jigawa_Nigeria,Jigawa,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1326,Kano_Nigeria,Kano,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327,Katsina_Nigeria,Katsina,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328,Kebbi_Nigeria,Kebbi,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.isnull().sum()

Province or State id                             0
Province or State                                0
Country                                          0
JHU                                           1464
COVID Tracking Project                        1548
NYT: Case Counts                              1548
ECDC                                          1581
WHO                                           1587
Apple                                         1003
University of Washington                      1493
COVID19 India                                 1566
Dipartimento della Protezione Civile          1582
South Korea Dataset                           1586
The World Bank: Global Health Statistics      1584
US Census Bureau: Demographic Estimates       1551
Google                                         559
Corona Data Scraper                            823
University of Oxford CGRT                     1595
PlaceIQ                                       1552
US Census Bureau: International Census        1580
Realtor.com                                   1552
Bureau of Economic Analysis                   1552
Swayable                                      1550
Opportunity Insights                          1552
US CDC: Select Demographic Characteristics    1557
COVID Racial Data Tracker                     1547
dtype: int64